### ISSUE TITLE
Installation problem on MACOS Mojave and Linux CentOS 7

### ISSUE THREAD

**Issue by Thibescobar** [dicomsort/dicomsort.com#5]
Hello,

I have difficulties to install DICOM sort.
On MACOS (Mojave 10.14.6), I downloaded the .dmg and extract the .app in the Applications folder but when I double click on the app, nothing happen...

On Linux (CentOS 7), I have difficulties to install from source (I will continue to try, but if you have advices it could be helpful).

Thank you very much for your help !

**Comment by suever** [comment]
@Thibescobar Are you getting a particular error when trying to install from source on linux?

**Comment by suever** [comment]
Going to close this as stale and since we have now release v3.0.0 of DICOM Sort which should address many of these issues
